"""add payments refunds tables

Revision ID: 70dfd157a4fb
Revises: be7c56902adb
Create Date: 2026-05-11 17:03:56.763328

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dfd157a4fb'
down_revision: Union[str, Sequence[str], None] = 'be7c56902adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('vnpay', 'offline_cash', name='paymentmethod'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='paymentstatus'), nullable=False),
    sa.Column('vnpay_txn_ref', sa.String(length=64), nullable=True),
    sa.Column('vnpay_response_code', sa.String(length=10), nullable=True),
    sa.Column('vnpay_payment_url', sa.Text(), nullable=True),
    sa.Column('url_expires_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_payment_amount'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vnpay_txn_ref')
    )
    op.create_index('idx_payments_booking_success', 'payments', ['booking_id'], unique=True, postgresql_where=sa.text("status = 'success'"))
    op.create_table('refunds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='refundstatus'), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_refund_amount'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('refunds')
    op.drop_index('idx_payments_booking_success', table_name='payments', postgresql_where=sa.text("status = 'success'"))
    op.drop_table('payments')
    sa.Enum(name='paymentmethod').drop(op.get_bind())
    sa.Enum(name='paymentstatus').drop(op.get_bind())
    sa.Enum(name='refundstatus').drop(op.get_bind())
