"""add unique name constraints to facilities courts

Revision ID: 5fa47f3c12c3
Revises: 59851aca699b
Create Date: 2026-05-11 01:36:14.768829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa47f3c12c3'
down_revision: Union[str, Sequence[str], None] = '59851aca699b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_court_facility_name', 'courts', ['facility_id', 'name'])
    op.create_unique_constraint('uq_facility_tenant_name', 'facilities', ['tenant_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_facility_tenant_name', 'facilities', type_='unique')
    op.drop_constraint('uq_court_facility_name', 'courts', type_='unique')
    # ### end Alembic commands ###
